---
- hosts: localhost
  gather_facts: no
  # vars_prompt:

  #   - name: vsphere_url
  #     prompt: What is your Vsphere IP?
  #     private: no

  #   - name: username
  #     prompt: What is your username Vsphere?
  #     private: no

    # - name: password
    #   prompt: What is your password Vsphere?
  tasks:
    - name: Clone From Template
      vmware_guest:
        hostname: "{{vm_hostname}}" ## IP Vsphere
        username: "{{vm_username}}"
        password: "{{vm_password}}"
        validate_certs: no
        name: "{{hostname}}"
        template: "{{template}}" ## Template Name
        datacenter: "{{datacenter}}" ## Cluster Name
        resource_pool: "{{resource_pool}}" ## Resource Name
        folder: "{{folder}}" # Folder
        cluster: "{{cluster}}" ## Cluster Name
        datastore: "{{datastore}}" ## Datastore Name
        hardware:
          memory_mb: "{{datastore}}"
          num_cpus: "{{datastore}}"
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: True
        networks:
          - name: "{{nw_name}}"
            ip: "{{ip}}"
            netmask: "{{nw_netmask}}"
            gateway: "{{nw_gateway}}"
            type: static
        customization:
          hostname: "{{hostname}}"
          dns_servers:
            - 10.198.101.39 # DNS Server1
            - 10.198.101.40 # DNS Server2
        state: poweredon
      delegate_to: localhost

# - name: Installation and Configuration redis 
#   hosts: redis
#   gather_facts: yes
#   become_user: root
#   become: yes 
#   roles:
#     - redis

# - name: Enable auto start and Start redis service
#   hosts: redis
#   become: yes
#   become_user: root
#   gather_facts: no
#   tasks:
#     - name: Enable auto start
#       command: systemctl enable redis_{{ redisport }}

#     - name: Restart for all server
#       reboot:



# - name: Cluster Create
#   hosts: r1
#   become_user: demo
#   become: yes
#   gather_facts: no
#   tasks:
#         - name: Create
#           command:  "{{ clustercommand }}"
#           ignore_errors: yes


# - name: Installation and Configuration mysql 
#   hosts: r1
#   gather_facts: yes
#   become: yes 
#   roles:
#     - mysql



