---
- hosts: localhost
  gather_facts: no
  # vars_prompt:

  #   - name: vsphere_url
  #     prompt: What is your Vsphere IP?
  #     private: no

  #   - name: username
  #     prompt: What is your username Vsphere?
  #     private: no

    # - name: password
    #   prompt: What is your password Vsphere?
  tasks:
    - name: Clone From Template
      vmware_guest:
        hostname: "10.10.15.23" ## IP Vsphere
        username: "eakasak.pib@truedigital.group"
        password: "Truedigital@2021"
        validate_certs: no
        name: "{{hostname}}"
        template: "D2T-Template-POC-ansible" ## Template Name
        datacenter: "TMP-VSAN-Datacenter" ## Cluster Name
        resource_pool: "Devops-Test" ## Resource Name
        folder: "DevOps - Testing" # Folder
        cluster: "Non-Production-VSAN-Cluster" ## Cluster Name
        datastore: "DSC_DB-NONPROD-TRUEID-01" ## Datastore Name
        hardware:
          memory_mb: "8192"
          num_cpus: "2"
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: True
        networks:
          - name: "DB-NON-Production(3265)"
            ip: "{{ip}}"
            netmask: "255.255.255.0"
            gateway: "10.100.65.1"
            type: static
        customization:
          hostname: "{{hostname}}"
          dns_servers:
            - 10.198.101.39 # DNS Server1
            - 10.198.101.40 # DNS Server2
        state: poweredon
      delegate_to: localhost

# - name: Installation and Configuration redis 
#   hosts: redis
#   gather_facts: yes
#   become_user: root
#   become: yes 
#   roles:
#     - redis

# - name: Enable auto start and Start redis service
#   hosts: redis
#   become: yes
#   become_user: root
#   gather_facts: no
#   tasks:
#     - name: Enable auto start
#       command: systemctl enable redis_{{ redisport }}

#     - name: Restart for all server
#       reboot:



# - name: Cluster Create
#   hosts: r1
#   become_user: demo
#   become: yes
#   gather_facts: no
#   tasks:
#         - name: Create
#           command:  "{{ clustercommand }}"
#           ignore_errors: yes


# - name: Installation and Configuration mysql 
#   hosts: r1
#   gather_facts: yes
#   become: yes 
#   roles:
#     - mysql



